name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Quality Gate
    runs-on: ubuntu-latest
    env:
      MANDACARU_POSTGRES_DB: "mandacaru_broker"
      MANDACARU_POSTGRES_USER: "time_dez"
      MANDACARU_POSTGRES_PASSWORD: "mandacaru"
      MANDACARU_POSTGRES_PORT: 5432
      MANDACARU_JWT_SECRET: mandacaru-jwt-secret
      MANDACARU_TEST_POSTGRES_DB: "mandacaru_broker_test"
      MANDACARU_TEST_POSTGRES_USER: "time_dez_test"
      MANDACARU_TEST_POSTGRES_PASSWORD: "mandacaru"
      MANDACARU_TEST_POSTGRES_PORT: 5433

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu"

      - name: Export environment variables
        run: export $(grep -v '^#' .env | xargs)

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Start Docker
        run: docker-compose up -d db-test

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=mandacaru-broker_mandacaru-broker-api

      - name: Sonar Cloud Coverage
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Pcoverage -Dsonar.projectKey=mandacaru-broker_mandacaru-broker-api

      - name: Stop Docker
        run: docker-compose down
