name: Run test suites
on:
  push:
  # pull_request:
  #   types: [opened, synchronize, reopened]
  #   branches:
  #     - main

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true -X

      - name: Run tests
        run: mvn test -X

  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    env:
      MANDACARU_POSTGRES_DB: "mandacaru_broker"
      MANDACARU_POSTGRES_USER: "time_dez"
      MANDACARU_POSTGRES_PASSWORD: "mandacaru"
      MANDACARU_POSTGRES_PORT: 5433
      MANDACARU_TEST_POSTGRES_PORT: 5432
      MANDACARU_TEST_POSTGRES_DB: "mandacaru_broker_test"
      MANDACARU_TEST_POSTGRES_USER: "time_dez_test"
      MANDACARU_TEST_POSTGRES_PASSWORD: "mandacaru"

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true -X

      - name: Start Docker
        run: docker-compose up -d db-test

      - name: Run tests
        run: mvn failsafe:integration-test

      - name: Stop Docker
        run: docker-compose down
